### ISSUE TITLE
swift version

### ISSUE THREAD

**Issue by y25zhao** [rob-nash/RRNCollapsableSectionTableView#2]
Hey, can you also support swift? Thanks

**Comment by rob-nash** [comment]
Closing as this is not a valid issue.

**Comment by y25zhao** [comment]
I implemented my own in swift anyway.... thx for sharing

**Comment by rob-nash** [comment]
You can now find a swift version on my profile.

**Comment by unittesting0** [comment]
@rob-nash I can't find the swift version?

**Comment by rob-nash** [comment]
Maintaining both was too much effort, so I removed the youngest one. The older Obj-C version remains. Sorry.

**Comment by rob-nash** [comment]
Ok finally caved in. Swift version here.
https://github.com/rob-nash/CollapsibleTable
